name: Dúvida ou Pergunta de Arquitetura
description: Solicitar ajuda, clarificações sobre documentação ou ADRs
labels: ["question"]
body:
  - type: textarea
    id: pergunta
    attributes:
      label: Qual é a sua dúvida?
      description: Descreva em detalhes o que você não conseguiu compreender ou precisa de debate.
    validations:
      required: true
  - type: textarea
    id: contexto
    attributes:
      label: Contexto adicional
      description: Em que parte do código ou ADR você se baseou?
    validations:
      required: false
