export enum RequestStatus {
  ABERTA = 'ABERTA',
  PROPOSTAS = 'PROPOSTAS',
  NEGOCIACAO = 'NEGOCIACAO',
  ACEITA = 'ACEITA',
  EM_EXECUCAO = 'EM_EXECUCAO',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
  EXPIRADA = 'EXPIRADA',
  RECUSADA = 'RECUSADA'
}
